//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int idProduct { get; set; }
        public string NameProduct { get; set; }
        public string PhotoProduct { get; set; }
        public string PriceProduct { get; set; }
        public int idTypeProduct { get; set; }
    
        public virtual TypeProduct TypeProduct { get; set; }
    }
}
